
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
CREATE TABLE notes (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
content VARCHAR(30) NOT NULL,
created_at TIMESTAMP,
updated_at TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table posts;
drop table comments;
CREATE TABLE posts (
id BIGINT(20) UNSIGNED AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
content TEXT,
description VARCHAR(250),
PRIMARY KEY(id),
created_time DATETIME,
updated_time DATETIME
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE comments (
id BIGINT(20) UNSIGNED AUTO_INCREMENT,
post_id BIGINT(20) UNSIGNED NOT NULL, 
PRIMARY KEY(id),
FOREIGN KEY (post_id) REFERENCES posts (id)
      ON DELETE RESTRICT ON UPDATE CASCADE,
content TEXT,
created_time DATETIME,
updated_time DATETIME
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

